#!/bin/bash
git config --global user.email "githubfortyuds@gmail.com"

git add -v .

git commit -m "commit"
git remote add teaching https://github.com/BRICOMATA9/Formation.git

git push -u -f teaching master
firefox https://github.com/BRICOMATA9/Formation.git

