#!/bin/sh

mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
filename=Formation
cd "$directory"

git config --global user.email "githubfortyuds@gmail.com"
git remote add $filename git+ssh://git@github.com/BRICOMATA9/$filename.git

git add -v . 
git commit -m "commit"
git push -u -f $filename master
#firefox https://github.com/BRICOMATA8/$filename.git

