/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.EnseignantDAO;
import DAO.EtudiantDAO;
import DAO.GroupeDAO;
import DAO.SalleDAO;
import Entities.Enseignant;
import Entities.Etudiant;
import Entities.Groupe;
import Entities.Salle;
import Utils.Tools;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hajji
 */
public class schedular extends javax.swing.JFrame {

    List<Salle> listSalle = SalleDAO.getInstance().displayAllSalle();
    List<Groupe> listGroupe = GroupeDAO.getInstance().displayAllGroupe();
    List<Enseignant> listEnseignant = EnseignantDAO.getInstance().displayAllEnseignant();
    List<Etudiant> listEtudiant = EtudiantDAO.getInstance().displayAllEtudiant();

    /**
     * Creates new form schedular
     */
    public schedular() {
        initComponents();
        btnModifier.setEnabled(false);
        btnSupprimer.setEnabled(false);
        btnModifierEtudiant.setEnabled(false);
        btnSupprimerEtudiant.setEnabled(false);
        btnModifierEnseignant.setEnabled(false);
        btnSupprimerEnseignant.setEnabled(false);
        initJtableSalle(listSalle);
        initJtableGroupe(listGroupe);
        initJtableEnseignant(listEnseignant);
        initJtableEtudiant(listEtudiant);
        btnModifierGroupe.setEnabled(false);
        btnSupprimerGroupe.setEnabled(false);
        FillComboBox(cbType, Tools.typeSalle);
        FillComboBox(cbPredecesseur, SalleDAO.getInstance().displayAllSalle());
        FillComboBox(cbSuccesseur, SalleDAO.getInstance().displayAllSalle());
        FillComboBox(cbGroupeEtudiant, GroupeDAO.getInstance().displayAllGroupe());
        FillComboBox(cbNiveau, Tools.niveauEtudiant);
        FillComboBox(cbSpecialiteEnseignant, Tools.specialiteEnseignant);
        FillComboBox(cbRechercheGroupe,GroupeDAO.getInstance().displayAllGroupe());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSalle = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldRechercheSalle = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Prédecesseur = new javax.swing.JLabel();
        tfLibelle = new javax.swing.JTextField();
        cbPredecesseur = new javax.swing.JComboBox<>();
        cbSuccesseur = new javax.swing.JComboBox<>();
        cbType = new javax.swing.JComboBox<>();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        sCapacite = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEnseignant = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        tfRechercheEnseignant = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfNomEnseignant = new javax.swing.JTextField();
        tfPrenomEnseignant = new javax.swing.JTextField();
        btnAjouterEnseignant = new javax.swing.JButton();
        btnModifierEnseignant = new javax.swing.JButton();
        btnSupprimerEnseignant = new javax.swing.JButton();
        cbSpecialiteEnseignant = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableEtudiant = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        tfRechercheEtudiant = new javax.swing.JTextField();
        cbRechercheGroupe = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNomEtudiant = new javax.swing.JTextField();
        tfPrenomEtudiant = new javax.swing.JTextField();
        cbGroupeEtudiant = new javax.swing.JComboBox<>();
        btnAjouterEtudiant = new javax.swing.JButton();
        btnModifierEtudiant = new javax.swing.JButton();
        btnSupprimerEtudiant = new javax.swing.JButton();
        cbNiveau = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGroupe = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnAjouterGroupe = new javax.swing.JButton();
        btnModifierGroupe = new javax.swing.JButton();
        btnSupprimerGroupe = new javax.swing.JButton();
        tfLibelleGroupe = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableSalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableSalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableSalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSalle);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Recherche"));
        jPanel6.setToolTipText("Filtres de recherche");

        jTextFieldRechercheSalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRechercheSalleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldRechercheSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldRechercheSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Gestion des Salles"));

        jLabel1.setText("Libelle");

        jLabel2.setText("Type");

        jLabel3.setText("Capacité");

        jLabel4.setText("Successeur");

        Prédecesseur.setText("Prédecesseur");

        cbPredecesseur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aucun" }));

        cbSuccesseur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aucun" }));

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aucun" }));
        cbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        sCapacite.setModel(new javax.swing.SpinnerNumberModel(20, null, null, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAjouter)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifier)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupprimer))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Prédecesseur))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfLibelle)
                            .addComponent(cbPredecesseur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSuccesseur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbType, javax.swing.GroupLayout.Alignment.TRAILING, 0, 135, Short.MAX_VALUE)
                            .addComponent(sCapacite, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbSuccesseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prédecesseur)
                    .addComponent(cbPredecesseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Salles", jPanel1);

        jTableEnseignant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEnseignant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnseignantMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableEnseignant);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Recherche"));

        tfRechercheEnseignant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRechercheEnseignantKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tfRechercheEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(484, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(tfRechercheEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Gestion des Enseignants"));

        jLabel17.setText("Nom");

        jLabel18.setText("Prénom");

        jLabel19.setText("Spécialité");

        btnAjouterEnseignant.setText("Ajouter");
        btnAjouterEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterEnseignantActionPerformed(evt);
            }
        });

        btnModifierEnseignant.setText("Modifier");
        btnModifierEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierEnseignantActionPerformed(evt);
            }
        });

        btnSupprimerEnseignant.setText("Supprimer");
        btnSupprimerEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerEnseignantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNomEnseignant)
                            .addComponent(tfPrenomEnseignant)
                            .addComponent(cbSpecialiteEnseignant, 0, 139, Short.MAX_VALUE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjouterEnseignant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModifierEnseignant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimerEnseignant)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfNomEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfPrenomEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbSpecialiteEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifierEnseignant)
                    .addComponent(btnAjouterEnseignant)
                    .addComponent(btnSupprimerEnseignant))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Enseignants", jPanel3);

        jTableEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEtudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEtudiantMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableEtudiant);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Recherche"));

        tfRechercheEtudiant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRechercheEtudiantKeyReleased(evt);
            }
        });

        cbRechercheGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRechercheGroupeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tfRechercheEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cbRechercheGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRechercheEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRechercheGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Gestion des Etudiants"));

        jLabel5.setText("Nom");

        jLabel6.setText("Prénom");

        jLabel7.setText("Niveau");

        jLabel8.setText("Groupe");

        btnAjouterEtudiant.setText("Ajouter");
        btnAjouterEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterEtudiantActionPerformed(evt);
            }
        });

        btnModifierEtudiant.setText("Modifier");
        btnModifierEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierEtudiantActionPerformed(evt);
            }
        });

        btnSupprimerEtudiant.setText("Supprimer");
        btnSupprimerEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerEtudiantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNomEtudiant)
                            .addComponent(tfPrenomEtudiant)
                            .addComponent(cbGroupeEtudiant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNiveau, 0, 139, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnAjouterEtudiant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModifierEtudiant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSupprimerEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPrenomEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbGroupeEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterEtudiant)
                    .addComponent(btnModifierEtudiant)
                    .addComponent(btnSupprimerEtudiant))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableGroupe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableGroupe);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Gestion des Groupes"));

        jLabel20.setText("Libelle");

        btnAjouterGroupe.setText("Ajouter");
        btnAjouterGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterGroupeActionPerformed(evt);
            }
        });

        btnModifierGroupe.setText("Modifier");

        btnSupprimerGroupe.setText("Supprimer");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(tfLibelleGroupe))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addComponent(btnAjouterGroupe)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifierGroupe)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupprimerGroupe)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfLibelleGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterGroupe)
                    .addComponent(btnModifierGroupe)
                    .addComponent(btnSupprimerGroupe))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addGap(8, 8, 8))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Etudiants", jPanel4);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Recherche"));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "créneau", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setAutoscrolls(false);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setFocusTraversalPolicy(null);
        jTable1.setFocusTraversalPolicyProvider(true);
        jTable1.setGridColor(new java.awt.Color(51, 51, 255));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setRowHeight(100);
        jScrollPane5.setViewportView(jTable1);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Gestion des Cours"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plans des Cours", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Salles");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRechercheSalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechercheSalleKeyReleased
        initRecherche(jTextFieldRechercheSalle.getText(), jTableSalle);
    }//GEN-LAST:event_jTextFieldRechercheSalleKeyReleased

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        Salle s = new Salle(cbType.getSelectedItem().toString(), tfLibelle.getText(),
                SalleDAO.getInstance().findSalleByLibelle(cbSuccesseur.getSelectedItem().toString()),
                SalleDAO.getInstance().findSalleByLibelle(cbPredecesseur.getSelectedItem().toString()),
                parseInt(sCapacite.getValue().toString()));
        SalleDAO.getInstance().insertSalle(s);
        if (SalleDAO.getInstance().insertSalle(s)) {
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès");
            initJtableSalle(SalleDAO.getInstance().displayAllSalle());
            FillComboBox(cbPredecesseur, SalleDAO.getInstance().displayAllSalle());
            FillComboBox(cbSuccesseur,SalleDAO.getInstance().displayAllSalle());
            cbType.setSelectedIndex(0);
            cbPredecesseur.setSelectedIndex(0);
            cbSuccesseur.setSelectedIndex(0);
            sCapacite.setValue(20);
            tfLibelle.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "l'Ajout a échoué");
        }

    }//GEN-LAST:event_btnAjouterActionPerformed

    private void cbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeActionPerformed

    private void jTableSalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSalleMouseClicked
        int rowIndex = jTableSalle.getSelectedRow();
        int id = Integer.parseInt(jTableSalle.getModel().getValueAt(rowIndex, 0).toString());
        Salle s = SalleDAO.getInstance().findSalleById(id);
        tfLibelle.setText(s.getLibelle());
        cbType.setSelectedItem(s.getType());
        sCapacite.setValue(s.getCapacite());
        cbSuccesseur.setSelectedItem(s.getSuccesseur().toString());
        cbPredecesseur.setSelectedItem(s.getPredecesseur().toString());
        btnModifier.setEnabled(true);
        btnSupprimer.setEnabled(true);
        btnAjouter.setEnabled(false);
    }//GEN-LAST:event_jTableSalleMouseClicked

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        int rowIndex = jTableSalle.getSelectedRow();
        int id = Integer.parseInt(jTableSalle.getModel().getValueAt(rowIndex, 0).toString());
        Salle s = SalleDAO.getInstance().findSalleById(id);
        s.setLibelle(tfLibelle.getText());
        s.setCapacite(parseInt(sCapacite.getValue().toString()));
        s.setType(cbType.getSelectedItem().toString());
        s.setPredecesseur(SalleDAO.getInstance().findSalleByLibelle(cbPredecesseur.getSelectedItem().toString()));
        s.setSuccesseur(SalleDAO.getInstance().findSalleByLibelle(cbSuccesseur.getSelectedItem().toString()));

        if (SalleDAO.getInstance().updateSalle(s)) {
            JOptionPane.showMessageDialog(this, "Modification effectuée avec succès");
            initJtableSalle(SalleDAO.getInstance().displayAllSalle());
            FillComboBox(cbPredecesseur,SalleDAO.getInstance().displayAllSalle());
            FillComboBox(cbSuccesseur, SalleDAO.getInstance().displayAllSalle());
            cbType.setSelectedIndex(0);
            cbPredecesseur.setSelectedIndex(0);
            cbSuccesseur.setSelectedIndex(0);
            sCapacite.setValue(20);
            tfLibelle.setText("");
            btnModifier.setEnabled(false);
            btnSupprimer.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Modification échouée");
        }

    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment supprimer", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) {
            System.out.print("yes");
            int rowIndex = jTableSalle.getSelectedRow();
            int id = Integer.parseInt(jTableSalle.getModel().getValueAt(rowIndex, 0).toString());

            if (SalleDAO.getInstance().deleteSalleById(id)) {
                JOptionPane.showMessageDialog(this, "Suppression effectuée avec succès");
                initJtableSalle(SalleDAO.getInstance().displayAllSalle());
                FillComboBox(cbPredecesseur,SalleDAO.getInstance().displayAllSalle());
                FillComboBox(cbSuccesseur, SalleDAO.getInstance().displayAllSalle());
                cbType.setSelectedIndex(0);
                cbPredecesseur.setSelectedIndex(0);
                cbSuccesseur.setSelectedIndex(0);
                sCapacite.setValue(20);
                tfLibelle.setText("");
                btnModifier.setEnabled(false);
                btnSupprimer.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Suppression échouée");
            }
        } else {
            System.out.print("no");
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void tfRechercheEtudiantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRechercheEtudiantKeyReleased
        initRecherche(tfRechercheEtudiant.getText(), jTableEtudiant);
    }//GEN-LAST:event_tfRechercheEtudiantKeyReleased

    private void btnAjouterEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterEtudiantActionPerformed
        Etudiant e = new Etudiant(tfNomEtudiant.getText(), tfPrenomEtudiant.getText(), cbNiveau.getSelectedItem().toString(), GroupeDAO.getInstance().findGroupeByLibelle(cbGroupeEtudiant.getSelectedItem().toString()));

        if (EtudiantDAO.getInstance().insertEtudiant(e)) {
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès");
            initJtableEtudiant(EtudiantDAO.getInstance().displayAllEtudiant());
            FillComboBox(cbGroupeEtudiant, GroupeDAO.getInstance().displayAllGroupe());
            cbGroupeEtudiant.setSelectedIndex(0);
            cbNiveau.setSelectedIndex(0);
            tfNomEtudiant.setText("");
            tfPrenomEtudiant.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "l'Ajout a échoué");
        }
    }//GEN-LAST:event_btnAjouterEtudiantActionPerformed

    private void btnModifierEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierEtudiantActionPerformed
        int rowIndex = jTableEtudiant.getSelectedRow();
        int id = Integer.parseInt(jTableEtudiant.getModel().getValueAt(rowIndex, 0).toString());
        Etudiant e = EtudiantDAO.getInstance().findEtudiantById(id);
        e.setNom(tfNomEtudiant.getText());
        e.setPrenom(tfPrenomEtudiant.getText());
        e.setNiveau(cbNiveau.getSelectedItem().toString());
        e.setGroupe(GroupeDAO.getInstance().findGroupeByLibelle(cbGroupeEtudiant.getSelectedItem().toString()));
        System.out.println(e.getNom() + " " + e.getPrenom() + " " + e.getGroupe().getLibelle() + "**************" + e.getGroupe().getId());
        if (EtudiantDAO.getInstance().updateEtudiant(e)) {
            JOptionPane.showMessageDialog(this, "Modification effectuée avec succès");
            initJtableEtudiant(EtudiantDAO.getInstance().displayAllEtudiant());
            FillComboBox(cbGroupeEtudiant, GroupeDAO.getInstance().displayAllGroupe());
            cbGroupeEtudiant.setSelectedIndex(0);
            cbNiveau.setSelectedIndex(0);
            tfNomEtudiant.setText("");
            tfPrenomEtudiant.setText("");
            btnModifierEtudiant.setEnabled(false);
            btnSupprimerEtudiant.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Modification échouée");
        }
    }//GEN-LAST:event_btnModifierEtudiantActionPerformed

    private void btnSupprimerEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerEtudiantActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment supprimer", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) {
            System.out.print("yes");
            int rowIndex = jTableEtudiant.getSelectedRow();
            int id = Integer.parseInt(jTableEtudiant.getModel().getValueAt(rowIndex, 0).toString());

            if (EtudiantDAO.getInstance().deleteEtudiantById(id)) {
                JOptionPane.showMessageDialog(this, "Suppression effectuée avec succès");
                initJtableEtudiant(EtudiantDAO.getInstance().displayAllEtudiant());
                FillComboBox(cbGroupeEtudiant, GroupeDAO.getInstance().displayAllGroupe());
                cbGroupeEtudiant.setSelectedIndex(0);
                cbNiveau.setSelectedIndex(0);
                tfNomEtudiant.setText("");
                tfPrenomEtudiant.setText("");
                btnModifierEtudiant.setEnabled(false);
                btnSupprimerEtudiant.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Suppression échouée");
            }
        } else {
            System.out.print("no");
        }
    }//GEN-LAST:event_btnSupprimerEtudiantActionPerformed

    private void jTableEtudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEtudiantMouseClicked
        int rowIndex = jTableEtudiant.getSelectedRow();
        int id = Integer.parseInt(jTableEtudiant.getModel().getValueAt(rowIndex, 0).toString());
        Etudiant e = EtudiantDAO.getInstance().findEtudiantById(id);
        tfNomEtudiant.setText(e.getNom());
        tfPrenomEtudiant.setText(e.getPrenom());
        cbNiveau.setSelectedItem(e.getNiveau());
        cbGroupeEtudiant.setSelectedItem(e.getGroupe().toString());
        btnModifierEtudiant.setEnabled(true);
        btnSupprimerEtudiant.setEnabled(true);

    }//GEN-LAST:event_jTableEtudiantMouseClicked

    private void tfRechercheEnseignantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRechercheEnseignantKeyReleased
        initRecherche(tfRechercheEnseignant.getText(), jTableEnseignant);
    }//GEN-LAST:event_tfRechercheEnseignantKeyReleased

    private void btnAjouterEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterEnseignantActionPerformed
        Enseignant e = new Enseignant(tfNomEnseignant.getText(), tfPrenomEnseignant.getText(), cbSpecialiteEnseignant.getSelectedItem().toString());

        if (EnseignantDAO.getInstance().insertEnseignant(e)) {
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès");
            initJtableEnseignant(EnseignantDAO.getInstance().displayAllEnseignant());
            FillComboBox(cbSpecialiteEnseignant, Tools.specialiteEnseignant);
            cbSpecialiteEnseignant.setSelectedIndex(0);

            tfNomEnseignant.setText("");
            tfPrenomEnseignant.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "l'Ajout a échoué");
        }
    }//GEN-LAST:event_btnAjouterEnseignantActionPerformed

    private void btnModifierEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierEnseignantActionPerformed
        int rowIndex = jTableEnseignant.getSelectedRow();
        int id = Integer.parseInt(jTableEnseignant.getModel().getValueAt(rowIndex, 0).toString());
        Enseignant e = EnseignantDAO.getInstance().findEnseignantById(id);
        e.setNom(tfNomEnseignant.getText());
        e.setPrenom(tfPrenomEnseignant.getText());
        e.setSpecialite(cbSpecialiteEnseignant.getSelectedItem().toString());
        if (EnseignantDAO.getInstance().updateEnseignant(e)) {
            JOptionPane.showMessageDialog(this, "Modification effectuée avec succès");
            initJtableEnseignant(EnseignantDAO.getInstance().displayAllEnseignant());
            FillComboBox(cbSpecialiteEnseignant, Tools.specialiteEnseignant);
            cbSpecialiteEnseignant.setSelectedIndex(0);
            tfNomEnseignant.setText("");
            tfPrenomEnseignant.setText("");
            btnModifierEnseignant.setEnabled(false);
            btnSupprimerEnseignant.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Modification échouée");
        }
    }//GEN-LAST:event_btnModifierEnseignantActionPerformed

    private void btnSupprimerEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerEnseignantActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment supprimer", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) {
            System.out.print("yes");
            int rowIndex = jTableEnseignant.getSelectedRow();
            int id = Integer.parseInt(jTableEnseignant.getModel().getValueAt(rowIndex, 0).toString());

            if (EnseignantDAO.getInstance().deleteEnseignantById(id)) {
                JOptionPane.showMessageDialog(this, "Suppression effectuée avec succès");
                initJtableEnseignant(EnseignantDAO.getInstance().displayAllEnseignant());
                FillComboBox(cbSpecialiteEnseignant, Tools.specialiteEnseignant);
                cbSpecialiteEnseignant.setSelectedIndex(0);
                tfNomEnseignant.setText("");
                tfPrenomEnseignant.setText("");
                btnModifierEnseignant.setEnabled(false);
                btnSupprimerEnseignant.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Suppression échouée");
            }
        } else {
            System.out.print("no");
        }
    }//GEN-LAST:event_btnSupprimerEnseignantActionPerformed

    private void jTableEnseignantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnseignantMouseClicked
       int rowIndex = jTableEnseignant.getSelectedRow();
        int id = Integer.parseInt(jTableEnseignant.getModel().getValueAt(rowIndex, 0).toString());
        Enseignant e = EnseignantDAO.getInstance().findEnseignantById(id);
        tfNomEnseignant.setText(e.getNom());
        tfPrenomEnseignant.setText(e.getPrenom());
        cbSpecialiteEnseignant.setSelectedItem(e.getSpecialite());
        btnModifierEnseignant.setEnabled(true);
        btnSupprimerEnseignant.setEnabled(true);
    }//GEN-LAST:event_jTableEnseignantMouseClicked

    private void cbRechercheGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRechercheGroupeActionPerformed
        
        try {
            initRecherche(cbRechercheGroupe.getSelectedItem().toString(), jTableEtudiant);
        } catch (NullPointerException e) {
            
        }

    }//GEN-LAST:event_cbRechercheGroupeActionPerformed

    private void btnAjouterGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterGroupeActionPerformed
        Groupe g = new Groupe(tfLibelleGroupe.getText());

        if (GroupeDAO.getInstance().insertGroupe(g)) {
            JOptionPane.showMessageDialog(this, "Ajout effectué avec succès");
            initJtableGroupe(GroupeDAO.getInstance().displayAllGroupe());
            FillComboBox(cbGroupeEtudiant, GroupeDAO.getInstance().displayAllGroupe());
            FillComboBox(cbRechercheGroupe, GroupeDAO.getInstance().displayAllGroupe());
            tfLibelleGroupe.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "l'Ajout a échoué");
        }
    }//GEN-LAST:event_btnAjouterGroupeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(schedular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(schedular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(schedular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(schedular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new schedular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Prédecesseur;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAjouterEnseignant;
    private javax.swing.JButton btnAjouterEtudiant;
    private javax.swing.JButton btnAjouterGroupe;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnModifierEnseignant;
    private javax.swing.JButton btnModifierEtudiant;
    private javax.swing.JButton btnModifierGroupe;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnSupprimerEnseignant;
    private javax.swing.JButton btnSupprimerEtudiant;
    private javax.swing.JButton btnSupprimerGroupe;
    private javax.swing.JComboBox<String> cbGroupeEtudiant;
    private javax.swing.JComboBox<String> cbNiveau;
    private javax.swing.JComboBox<String> cbPredecesseur;
    private javax.swing.JComboBox<String> cbRechercheGroupe;
    private javax.swing.JComboBox<String> cbSpecialiteEnseignant;
    private javax.swing.JComboBox<String> cbSuccesseur;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEnseignant;
    private javax.swing.JTable jTableEtudiant;
    private javax.swing.JTable jTableGroupe;
    private javax.swing.JTable jTableSalle;
    private javax.swing.JTextField jTextFieldRechercheSalle;
    private javax.swing.JSpinner sCapacite;
    private javax.swing.JTextField tfLibelle;
    private javax.swing.JTextField tfLibelleGroupe;
    private javax.swing.JTextField tfNomEnseignant;
    private javax.swing.JTextField tfNomEtudiant;
    private javax.swing.JTextField tfPrenomEnseignant;
    private javax.swing.JTextField tfPrenomEtudiant;
    private javax.swing.JTextField tfRechercheEnseignant;
    private javax.swing.JTextField tfRechercheEtudiant;
    // End of variables declaration//GEN-END:variables

    public void initJtableSalle(List<Salle> listeSalle) {
        ModelTableSalle mts = new ModelTableSalle();
        mts.addColumn("Id");
        mts.addColumn("Libelle");
        mts.addColumn("Type");
        mts.addColumn("Capacité");
        for (int i = 0; i < listeSalle.size(); i++) {
            mts.addRow(listeSalle.get(i));
        }
        jTableSalle.setModel(mts.Get());
        btnAjouter.setEnabled(true);
    }

    public void initJtableGroupe(List<Groupe> listeGroupe) {
        ModelTableGroupe mtg = new ModelTableGroupe();
        mtg.addColumn("Id");
        mtg.addColumn("Nom Du Groupe");
        mtg.addColumn("Nombre d'étudiants");
        for (int i = 0; i < listeGroupe.size(); i++) {
            mtg.addRow(listeGroupe.get(i));
        }
        jTableGroupe.setModel(mtg.Get());

    }

    public void initJtableEnseignant(List<Enseignant> listeEnseignant) {
        ModelTableEnseignant mte = new ModelTableEnseignant();
        mte.addColumn("Id");
        mte.addColumn("Nom");
        mte.addColumn("Prénom");
        mte.addColumn("Spécialité");
        for (int i = 0; i < listeEnseignant.size(); i++) {
            mte.addRow(listeEnseignant.get(i));
        }
        jTableEnseignant.setModel(mte.Get());

    }

    public void initJtableEtudiant(List<Etudiant> listeEtudiant) {
        ModelTableEtudiant mte = new ModelTableEtudiant();
        mte.addColumn("Id");
        mte.addColumn("Nom");
        mte.addColumn("Prénom");
        mte.addColumn("Niveau");
        mte.addColumn("Groupe");
        for (int i = 0; i < listeEtudiant.size(); i++) {
            mte.addRow(listeEtudiant.get(i));
        }
        jTableEtudiant.setModel(mte.Get());

    }

    void initRecherche(String query, JTable jt) {
        DefaultTableModel dtm = (DefaultTableModel) jt.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dtm);
        jt.setRowSorter(tr);
        tr.setRowFilter(javax.swing.RowFilter.regexFilter(query));
    }

    public void FillComboBox(JComboBox cb, List list) {
        List<String>lista=new ArrayList<>();
        list.stream().forEach((object)->lista.add(object.toString()));
        Collections.sort(lista,(String a,String b)->{return a.compareTo(b);});
        cb.removeAllItems();
        cb.addItem("");
        lista.stream().forEach((object) -> {
            cb.addItem(object);
        });
    }
}
