#!/usr/bin/bash

old_IFS=$IFS;
counter=0;
patternPath=$2;
if [ $# != 2 ]; then
  echo "USAGE: mvmp3 [music_root_directory] [new_path]";
  echo "Example: ./mvmp3 ./music \"/home/musicplayer/music/?artist?/?year? ?album?/?track? - ?title?\"";
  exit; 
fi

function mvfile {
  path="";
  artist="";  #TPE
  track=""; #TRCK
  title=""; #TIT
  album=""; #TALB
  year=""; #TYER
  style=""; #TCON
  filename=$(basename "$1");
  extension="${filename##*.}";
  IFS=$'\n';
  echo "> Treating $1";
  for line in `id3info "$1"`; do
    if [ ${line:4:3} = "TPE" ]; then
      artist=`echo $line | sed 's,.*: \(.*\),\1,'`;
    else if [ ${line:4:4} = "TRCK" ]; then
      track=`echo $line | sed 's,.*: \(.*\),\1,'`;
    else if [ ${line:4:3} = "TIT" ]; then
      title=`echo $line | sed 's,.*: \(.*\),\1,'`;
    else if [ ${line:4:4} = "TALB" ]; then
      album=`echo $line | sed 's,.*: \(.*\),\1,'`;
    else if [ ${line:4:4} = "TYER" ]; then
      year=`echo $line | sed 's,.*: \(.*\),\1,'`;
    else if [ ${line:4:4} = "TCON" ]; then
      style=`echo $line | sed 's,.*: \(.*\),\1,'`;
    fi fi fi fi fi fi
  done;
  IFS=$old_IFS;
  if [[ "$patternPath" == *?artist?* && $artist == "" ]]; then
    echo ">>> Unable to move $1: Artist not found";
    return;
  fi
  if [[ "$patternPath" == *?track?* && $track == "" ]]; then
    echo ">>> Unable to move $1: [track] not found";
    return;
  fi
  if [[ "$patternPath" == *?title?* && $title == "" ]]; then
    echo ">>> Unable to move $1: [title] not found";
    return;
  fi
  if [[ "$patternPath" == *?album?* && $album == "" ]]; then
    echo ">>> Unable to move $1: [album] not found";
    return;
  fi
  if [[ "$patternPath" == *?year?* && $year == "" ]]; then
    echo ">>> Unable to move $1: [year] not found";
    return;
  fi
  if [[ "$patternPath" == *?style?* && $style == "" ]]; then
    echo "Unable to move $1: [style] not found";
    return;
  fi
  path=`echo $patternPath | sed -e "s,?artist?,$artist,g" -e "s,?track?,$track,g" -e "s,?title?,$title,g" -e "s,?album?,$album,g" -e "s,?year?,$year,g" -e "s,?style?,$style,g"`;
  path="$path.$extension"
  dir=$(dirname "$path");
  if [[ -e "$path" ]]; then
    echo ">>> File '$path' already exists !";
    return;
  fi
  if [[ ! -d "$dir" ]]; then
    mkdir -p "$dir";
    echo ">>> creating path : $dir";
  fi
  echo ">>> moving file $1 to $path";
  mv "$1" "$path"
  counter=$(($counter + 1));
}

IFS=$'\n';
for filein in `find "$1" -type f -iregex '.*\.\(mp3\|flac\|m4a\|wav\|ogg\|wma\)'`; do
  mvfile "$filein";
done
IFS=$old_IFS;

echo;
echo "$counter files moved";
