// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: packimports(3) 

package ydoc.B;

import com.sun.javadoc.Tag;
import com.sun.tools.doclets.Taglet;
import ydoc.A.I;

// Referenced classes of package ydoc.B:
//            D

public abstract class C
    implements Taglet
{
    public static final class _A
        implements _B
    {

        public String B()
        {
            return A;
        }

        public String C()
        {
            return B;
        }

        public String A()
        {
            return C;
        }

        private final String A;
        private final String B;
        private final String C;

        public _A(String s, String s1)
        {
            String s2 = new String(I.D());
            A = C.B(s, s2);
            B = C.B(s, C.B(s2));
            C = s1;
        }
    }

    public static interface _B
    {

        public abstract String B();

        public abstract String C();

        public abstract String A();
    }


    protected C(D d)
    {
        A = d;
    }

    public D A()
    {
        return A;
    }

    public boolean inField()
    {
        return false;
    }

    public boolean inConstructor()
    {
        return false;
    }

    public boolean inMethod()
    {
        return false;
    }

    public boolean inOverview()
    {
        return true;
    }

    public boolean inPackage()
    {
        return true;
    }

    public boolean inType()
    {
        return true;
    }

    public boolean isInlineTag()
    {
        return false;
    }

    public String toString(Tag tag)
    {
        Tag atag[] = {
            tag
        };
        return toString(atag);
    }

    public String toString(Tag atag[])
    {
        return A.A(atag, null);
    }

    public static String C()
    {
        return B.A();
    }

    public static String B()
    {
        return B.B();
    }

    public static String D()
    {
        return B.C();
    }

    private static String A(String s)
    {
        int i = s.indexOf('_');
        if(i > -1)
            return s.substring(0, i);
        else
            return s;
    }

    private static String A(String s, String s1)
    {
        int i = s.indexOf("$(VERSION)");
        if(i > -1)
            return (new StringBuilder()).append(s.substring(0, i)).append(s1).append(s.substring(i + "$(VERSION)".length())).toString();
        else
            return s;
    }

    static String B(String s, String s1)
    {
        return A(s, s1);
    }

    static String B(String s)
    {
        return A(s);
    }

    public static _B B = new _A("generated by yWorks UML Doclet $(VERSION)", "http://www.yworks.com/");
    final D A;

}
