package modele;


import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.HeaderFooter;
import com.lowagie.text.List;
import com.lowagie.text.ListItem;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Section;


import vue.Popup_rapport_pdf;






public class Rapport_PDF {
	private static String FILE = "Rapport_PDF/SecondPdf.pdf";
	private static Font Font_Titre = new Font(Font.HELVETICA);
	private static Font Font_Sous_Titre = new Font(Font.HELVETICA);
	private static Font Font_Header=new Font(Font.TIMES_ROMAN);
	private static Font redFont = new Font(Font.BOLD);
	private static Font subFont = new Font(Font.BOLD);
	private static Font smallBold = new Font(Font.BOLD);

	

	// iText allows to add metadata to the PDF which can be viewed in your Adobe
	// Reader
	// under File -> Properties
	public static void addMetaData(Document document) {
		document.addTitle("Rapport PDF");
		document.addSubject("Rapport Activite Employes");
		document.addKeywords("Portefeuille de bourse, Gigaby'TSE, Rapport");
		document.addAuthor("Dentan Jeremie");
		document.addCreator("Dentan Jeremie");
	}



	public static void addTitlePage(Document document)
			throws DocumentException {

		Font_Titre.setSize(15);
		Font_Titre.setColor(Color.red);
		Font_Sous_Titre.setSize(10);
		Font_Sous_Titre.setColor(Color.blue);
		Font_Header.setSize(10);

		Paragraph Titre = new Paragraph();

		Titre.setAlignment(Element.ALIGN_CENTER);

		addEmptyLine(Titre, 1);

		Paragraph Titre_principal = new Paragraph("Rapport d'activite des employes", Font_Titre);
		Paragraph Sous_Titre = new Paragraph("("+Popup_rapport_pdf.date_depart+" - "+ Formatage_Date.mettredateenformepourstockage(new Date())+")", Font_Titre);

		Titre.add(Titre_principal);
		Titre.add(Sous_Titre);

		//Paragraph utilisateur = new Paragraph(System.getProperty("user.name"));
		SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
		
		Paragraph h= new Paragraph("Rapport d'activite des employes 																																																				"
				+ "																		"+format.format(new Date()),Font_Header);
		Paragraph Titre_Header = new Paragraph();

		h.setAlignment(Element.ALIGN_LEFT);
		Titre_Header.add(h);
		

		HeaderFooter header= new HeaderFooter(Titre_Header,false);
		header.setUseVariableBorders(false);

		Paragraph preface = new Paragraph();
		addEmptyLine(preface, 1);

		//preface.add(new Paragraph("Report generated by: " + System.getProperty("user.name") + ", " + new Date(), 
		//		smallBold));
		//addEmptyLine(preface, 3);
		//preface.add(new Paragraph("This document describes something which is very important ",
		//		smallBold));


		addEmptyLine(preface, 4);

		Phrase h1= new Phrase();	
		HeaderFooter footer1 = new HeaderFooter(h1,true);
		footer1.setAlignment(Element.ALIGN_RIGHT);
		
	
		document.setHeader(header);
		document.add(Titre);
		document.add(preface);
		document.setFooter(footer1);
		
	}

	public static void addContent(Document document, String date_depart) throws DocumentException {

		if(Popup_rapport_pdf.checkbox_tri_user.isSelected()==true){
			document.add(Recuperer_infos_rapport_pdf.informations_par_utilisateurs(date_depart));
		}else{
			if(Popup_rapport_pdf.checkbox_tri_entreprise.isSelected()==true){
				document.add(Recuperer_infos_rapport_pdf.informations_par_entreprise(date_depart));
			}
		}

	}

	/* private static void createTable(Section subCatPart)
      throws BadElementException {
    PdfPTable table = new PdfPTable(3);

    // t.setBorderColor(BaseColor.GRAY);
    // t.setPadding(4);
    // t.setSpacing(4);
    // t.setBorderWidth(1);

    PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("Table Header 2"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("Table Header 3"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(c1);
    table.setHeaderRows(1);

    table.addCell("1.0");
    table.addCell("1.1");
    table.addCell("1.2");
    table.addCell("2.1");
    table.addCell("2.2");
    table.addCell("2.3");

    subCatPart.add(table);

  }*/

	private static void createList(Section subCatPart) {
		List list = new List(true, false, 10);
		list.add(new ListItem("First point"));
		list.add(new ListItem("Second point"));
		list.add(new ListItem("Third point"));
		subCatPart.add(list);
	}

	public static void addEmptyLine(Paragraph paragraph, int number) {
		for (int i = 0; i < number; i++) {
			paragraph.add(new Paragraph(" "));
		}
	}
} 