#!/bin/sh

javadoc -docletpath /home/aghiles/Aghiles/Teaching/Java/lib/umlgraph-5.6.jar -doclet org.umlgraph.doclet.UmlGraph -package -attributes -operations -constructors -enumerations -views -visibility -types src/*/*.java
dot -Tpng -ograph.png graph.dot
