var __JSON;__JSON||(__JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function b(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var g=l[a];return"string"===typeof g?g:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,l){var g,e,f,d,h=m,p,r=l[a];r&&"object"===typeof r&&"function"===typeof r.to__JSON&&(r=r.to__JSON(a));"function"===typeof k&&(r=k.call(l,a,r));switch(typeof r){case "string":return b(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);
case "object":if(!r)return"null";m+=q;p=[];if("[object Array]"===Object.prototype.toString.apply(r)){d=r.length;for(g=0;g<d;g+=1)p[g]=c(g,r)||"null";f=0===p.length?"[]":m?"[\n"+m+p.join(",\n"+m)+"\n"+h+"]":"["+p.join(",")+"]";m=h;return f}if(k&&"object"===typeof k)for(d=k.length,g=0;g<d;g+=1)"string"===typeof k[g]&&(e=k[g],(f=c(e,r))&&p.push(b(e)+(m?": ":":")+f));else for(e in r)Object.prototype.hasOwnProperty.call(r,e)&&(f=c(e,r))&&p.push(b(e)+(m?": ":":")+f);f=0===p.length?"{}":m?"{\n"+m+p.join(",\n"+
m)+"\n"+h+"}":"{"+p.join(",")+"}";m=h;return f}}"function"!==typeof Date.prototype.to__JSON&&(Date.prototype.to__JSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.to__JSON=Number.prototype.to__JSON=Boolean.prototype.to__JSON=function(a){return this.valueOf()});var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m,q,l={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k;"function"!==typeof __JSON.stringify&&(__JSON.stringify=function(a,b,g){var e;q=m="";if("number"===typeof g)for(e=0;e<g;e+=1)q+=" ";else"string"===typeof g&&(q=g);if((k=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("__JSON.stringify");return c("",
{"":a})});"function"!==typeof __JSON.parse&&(__JSON.parse=function(a,b){function g(a,e){var l,c,k=a[e];if(k&&"object"===typeof k)for(l in k)Object.prototype.hasOwnProperty.call(k,l)&&(c=g(k,l),void 0!==c?k[l]=c:delete k[l]);return b.call(a,e,k)}var e;a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?g({"":e},""):e;throw new SyntaxError("__JSON.parse");})})();var BoxeverStorage=BoxeverStorage||{};
(function(){function a(){var a="{}";if("userDataBehavior"==s){f.load("bStorage");try{a=f.getAttribute("bStorage")}catch(b){}try{u=f.getAttribute("bStorage_update")}catch(g){}e.bStorage=a}h();l();k()}function b(){var w;clearTimeout(r);r=setTimeout(function(){if("localStorage"==s||"globalStorage"==s)w=e.bStorage_update;else if("userDataBehavior"==s){f.load("bStorage");try{w=f.getAttribute("bStorage_update")}catch(b){}}if(w&&w!=u){u=w;var l=t.parse(t.stringify(g.__bstorage_meta.CRC32)),k;a();k=t.parse(t.stringify(g.__bstorage_meta.CRC32));
var d,h=[],n=[];for(d in l)l.hasOwnProperty(d)&&(k[d]?l[d]!=k[d]&&"2."==String(l[d]).substr(0,2)&&h.push(d):n.push(d));for(d in k)k.hasOwnProperty(d)&&(l[d]||h.push(d));c(h,"updated");c(n,"deleted")}},25)}function c(a,b){a=[].concat(a||[]);if("flushed"==b){a=[];for(var l in p)p.hasOwnProperty(l)&&a.push(l);b="deleted"}l=0;for(var g=a.length;l<g;l++){if(p[a[l]])for(var e=0,k=p[a[l]].length;e<k;e++)p[a[l]][e](a[l],b);if(p["*"])for(e=0,k=p["*"].length;e<k;e++)p["*"][e](a[l],b)}}function d(){var a=(+new Date).toString();
"localStorage"==s||"globalStorage"==s?e.bStorage_update=a:"userDataBehavior"==s&&(f.setAttribute("bStorage_update",a),f.save("bStorage"));b()}function h(){if(e.bStorage)try{g=t.parse(String(e.bStorage))}catch(a){e.bStorage="{}"}else e.bStorage="{}";x=e.bStorage?String(e.bStorage).length:0;g.__bstorage_meta||(g.__bstorage_meta={});g.__bstorage_meta.CRC32||(g.__bstorage_meta.CRC32={})}function m(){if(g.__bstorage_meta.PubSub){for(var a=+new Date-2E3,b=0,l=g.__bstorage_meta.PubSub.length;b<l;b++)if(g.__bstorage_meta.PubSub[b][0]<=
a){g.__bstorage_meta.PubSub.splice(b,g.__bstorage_meta.PubSub.length-b);break}g.__bstorage_meta.PubSub.length||delete g.__bstorage_meta.PubSub}try{e.bStorage=t.stringify(g),f&&(f.setAttribute("bStorage",e.bStorage),f.save("bStorage")),x=e.bStorage?String(e.bStorage).length:0}catch(k){}}function q(a){if(!a||"string"!=typeof a&&"number"!=typeof a)throw new TypeError("Key name must be string or numeric");if("__bstorage_meta"==a)throw new TypeError("Reserved key name");return!0}function l(){var a,b,e,
k,f=Infinity,h=!1,n=[];clearTimeout(A);if(g.__bstorage_meta&&"object"==typeof g.__bstorage_meta.TTL){a=+new Date;e=g.__bstorage_meta.TTL;k=g.__bstorage_meta.CRC32;for(b in e)e.hasOwnProperty(b)&&(e[b]<=a?(delete e[b],delete k[b],delete g[b],h=!0,n.push(b)):e[b]<f&&(f=e[b]));Infinity!=f&&(A=setTimeout(l,f-a));h&&(m(),d(),c(n,"deleted"))}}function k(){var a;if(g.__bstorage_meta.PubSub){var b,l=y;for(a=g.__bstorage_meta.PubSub.length-1;0<=a;a--)if(b=g.__bstorage_meta.PubSub[a],b[0]>y){var l=b[0],e=b[1];
b=b[2];if(v[e])for(var k=0,c=v[e].length;k<c;k++)v[e][k](e,t.parse(t.stringify(b)))}y=l}}var n=window.jQuery||window.$||(window.$={}),t={parse:window.JSON&&(window.JSON.parse||window.JSON.decode)||window.__JSON&&window.__JSON.parse||__JSON&&__JSON.parse||String.prototype.evalJSON&&function(a){return String(a).evalJSON()}||n.parseJSON||n.evalJSON,stringify:Object.toJSON||window.JSON&&(window.JSON.stringify||window.JSON.encode)||window.__JSON&&window.__JSON.stringify||__JSON&&__JSON.stringify||n.toJSON};
if(!t.parse||!t.stringify)throw Error("No JSON support found, include //cdnjs.cloudflare.com/ajax/libs/json2/20110223/json2.js to page");var g={__bstorage_meta:{CRC32:{}}},e={bStorage:"{}"},f=null,x=0,s=!1,p={},r=!1,u=0,v={},y=+new Date,A,z={isXML:function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1},encode:function(a){if(!this.isXML(a))return!1;try{return(new XMLSerializer).serializeToString(a)}catch(b){try{return a.xml}catch(e){}}return!1},decode:function(a){var b=
"DOMParser"in window&&(new DOMParser).parseFromString||window.ActiveXObject&&function(a){var b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a);return b};if(!b)return!1;a=b.call("DOMParser"in window&&new DOMParser||window,a,"text/xml");return this.isXML(a)?a:!1}};BoxeverStorage={version:"0.4.3",set:function(a,b,e){q(a);e=e||{};if("undefined"==typeof b)return this.deleteKey(a),b;if(z.isXML(b))b={_is_xml:!0,xml:z.encode(b)};else{if("function"==typeof b)return;b&&"object"==typeof b&&
(b=t.parse(t.stringify(b)))}g[a]=b;for(var l=g.__bstorage_meta.CRC32,k=t.stringify(b),d=k.length,f=2538058380^d,h=0,n;4<=d;)n=k.charCodeAt(h)&255|(k.charCodeAt(++h)&255)<<8|(k.charCodeAt(++h)&255)<<16|(k.charCodeAt(++h)&255)<<24,n=1540483477*(n&65535)+((1540483477*(n>>>16)&65535)<<16),n^=n>>>24,n=1540483477*(n&65535)+((1540483477*(n>>>16)&65535)<<16),f=1540483477*(f&65535)+((1540483477*(f>>>16)&65535)<<16)^n,d-=4,++h;switch(d){case 3:f^=(k.charCodeAt(h+2)&255)<<16;case 2:f^=(k.charCodeAt(h+1)&255)<<
8;case 1:f^=k.charCodeAt(h)&255,f=1540483477*(f&65535)+((1540483477*(f>>>16)&65535)<<16)}f^=f>>>13;f=1540483477*(f&65535)+((1540483477*(f>>>16)&65535)<<16);l[a]="2."+((f^f>>>15)>>>0);this.setTTL(a,e.TTL||0);c(a,"updated");return b},get:function(a,b){q(a);return a in g?g[a]&&"object"==typeof g[a]&&g[a]._is_xml?z.decode(g[a].xml):g[a]:"undefined"==typeof b?null:b},deleteKey:function(a){q(a);return a in g?(delete g[a],"object"==typeof g.__bstorage_meta.TTL&&a in g.__bstorage_meta.TTL&&delete g.__bstorage_meta.TTL[a],
delete g.__bstorage_meta.CRC32[a],m(),d(),c(a,"deleted"),!0):!1},setTTL:function(a,b){var e=+new Date;q(a);b=Number(b)||0;return a in g?(g.__bstorage_meta.TTL||(g.__bstorage_meta.TTL={}),0<b?g.__bstorage_meta.TTL[a]=e+b:delete g.__bstorage_meta.TTL[a],m(),l(),d(),!0):!1},getTTL:function(a){var b=+new Date;q(a);return a in g&&g.__bstorage_meta.TTL&&g.__bstorage_meta.TTL[a]?(a=g.__bstorage_meta.TTL[a]-b)||0:0},flush:function(){g={__bstorage_meta:{CRC32:{}}};m();d();c(null,"flushed");return!0},storageObj:function(){function a(){}
a.prototype=g;return new a},index:function(){var a=[],b;for(b in g)g.hasOwnProperty(b)&&"__bstorage_meta"!=b&&a.push(b);return a},storageSize:function(){return x},currentBackend:function(){return s},storageAvailable:function(){return!!s},listenKeyChange:function(a,b){q(a);p[a]||(p[a]=[]);p[a].push(b)},stopListening:function(a,b){q(a);if(p[a])if(b)for(var e=p[a].length-1;0<=e;e--)p[a][e]==b&&p[a].splice(e,1);else delete p[a]},subscribe:function(a,b){a=(a||"").toString();if(!a)throw new TypeError("Channel not defined");
v[a]||(v[a]=[]);v[a].push(b)},publish:function(a,b){a=(a||"").toString();if(!a)throw new TypeError("Channel not defined");g.__bstorage_meta||(g.__bstorage_meta={});g.__bstorage_meta.PubSub||(g.__bstorage_meta.PubSub=[]);g.__bstorage_meta.PubSub.unshift([+new Date,a,b]);m();d()},reInit:function(){a()}};(function(){var a=!1;if("localStorage"in window)try{window.localStorage.setItem("_tmptest","tmpval"),a=!0,window.localStorage.removeItem("_tmptest")}catch(g){}if(a)try{window.localStorage&&(e=window.localStorage,
s="localStorage",u=e.bStorage_update)}catch(d){}else if("globalStorage"in window)try{window.globalStorage&&(e="localhost"==window.location.hostname?window.globalStorage["localhost.localdomain"]:window.globalStorage[window.location.hostname],s="globalStorage",u=e.bStorage_update)}catch(c){}else if(f=document.createElement("link"),f.addBehavior){f.style.behavior="url(#default#userData)";document.getElementsByTagName("head")[0].appendChild(f);try{f.load("bStorage")}catch(n){f.setAttribute("bStorage",
"{}"),f.save("bStorage"),f.load("bStorage")}a="{}";try{a=f.getAttribute("bStorage")}catch(t){}try{u=f.getAttribute("bStorage_update")}catch(m){}e.bStorage=a;s="userDataBehavior"}else{f=null;return}h();l();"localStorage"==s||"globalStorage"==s?"addEventListener"in window?window.addEventListener("storage",b,!1):document.attachEvent("onstorage",b):"userDataBehavior"==s&&setInterval(b,1E3);k();"addEventListener"in window&&window.addEventListener("pageshow",function(a){a.persisted&&b()},!1)})()})();
var BoxeverXML={isXML:function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1},string2xml:function(a){if(window.ActiveXObject){var b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a)}else b=(new DOMParser).parseFromString(a,"text/xml");return b},xml2string:function(a){var b=a.documentElement;return void 0==b.xml?(new XMLSerializer).serializeToString(a):b.xml},unescape:function(a){a=a.replace(/&lt;/gi,"\x3c");a=a.replace(/&gt;/gi,"\x3e");a=a.replace(/&quot;/gi,
'"');return a=a.replace(/&amp;/gi,"\x26")}},BoxeverJSONP={exec:function(a,b){var c="jsonp"+(100*Math.random()).toString(),c=c.replace(/\./g,"");a=a.replace("callback\x3d?","callback\x3d"+c);a=a.replace("cb\x3d?","cb\x3d"+c);window[c]=function(a){try{var h=document.getElementById(c);h.parentNode.removeChild(h)}catch(m){}"string"===typeof a&&(a=BoxeverXML.unescape(a),window.DOMParser?a=(new DOMParser).parseFromString(a,"text/xml"):(h=new ActiveXObject("Microsoft.XMLDOM"),h.async=!1,h.loadXML(a),a=h));
b(a);try{window[c]=null,delete window[c]}catch(q){}};document.getElementsByTagName("head")[0].appendChild(function(){var b=document.createElement("script");b.type="text/javascript";b.charset="UTF-8";b.src=a;b.async=!0;b.id=c;return b}())}},_boxever_settings=_boxever_settings||{},BoxeverJERS=BoxeverJERS||{errors:[]};
(function(){function a(a){var d=c+"/boxever-log-js-error.js?client_key\x3d"+b+"\x26message\x3d"+encodeURIComponent(a);document.getElementsByTagName("head")[0].appendChild(function(){var a=document.createElement("script");a.type="text/javascript";a.charset="UTF-8";a.src=d;return a}())}var b,c,d=BoxeverJERS.errors;BoxeverJERS.errors={push:function(){for(var b=0;b<arguments.length;b++)try{if("function"===typeof arguments[b])arguments[b]();else{var c=arguments[b],d={};"string"===typeof c?d.message=c:
(d.name="undefined"!==typeof c.name&&null!==c.name?c.name.toString():"",d.message="undefined"!==typeof c.message&&null!==c.message?c.message:"",d.stack="undefined"!==typeof c.stack&&null!==c.stack?c.stack:"");d.parent_url=document.location.href;var l=__JSON.stringify(d);a(l)}}catch(k){l={message:"Unknown error occured sending error report"},l=__JSON.stringify(l),a(l)}}};"[object Array]"===Object.prototype.toString.call(d)&&(BoxeverJERS.errors.push.apply(BoxeverJERS.errors,d),"undefined"!==typeof BoxeverJERS.settings&&
("undefined"!==typeof BoxeverJERS.settings.client_key&&(b=BoxeverJERS.settings.client_key),"undefined"!==typeof BoxeverJERS.settings.client_key&&(c=BoxeverJERS.settings.target)));this.validateSettings=function(a){if(!a.hasOwnProperty("client_key"))throw Error("Configuration property 'client_key' is required");if(!a.hasOwnProperty("target"))throw Error("Configuration property 'target' is required");};this.initSettings=function(){this.validateSettings(_boxever_settings);b=_boxever_settings.client_key;
c=_boxever_settings.target};this.init=function(){this.initSettings()};init()})();var _boxever_error_service=_boxever_error_service||{errors:[]};(function(){var a=_boxever_error_service.errors;"[object Array]"===Object.prototype.toString.call(a)&&BoxeverJERS.errors.push.apply(BoxeverJERS.errors,a);_boxever_error_service=BoxeverJERS})();
var BoxeverCrossDomain=BoxeverCrossDomain||function(){var a,b,c=1,d,h=this;return{postMessage:function(a,b,l){b&&(l=l||parent,h.postMessage?l.postMessage(a,b.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):b&&(l.location=b.replace(/#.*$/,"")+"#"+ +new Date+c++ +"\x26"+a))},receiveMessage:function(c,q){h.postMessage?(d&&(h.removeEventListener?h.removeEventListener("message",d,!1):h.detachEvent("onmessage",d)),c&&(d=function(a){if("string"===typeof q&&a.origin!==q||"[object Function]"===Object.prototype.toString.call(q)&&
!1===q(a.origin))return!1;c(a)},h.addEventListener?h.addEventListener("message",d,!1):h.attachEvent("onmessage",d))):(a&&clearInterval(a),a=null,c&&(a=setInterval(function(){var a=document.location.hash,k=/^#?\d+&/;a!==b&&k.test(a)&&(b=a,c({data:a.replace(k,"")}))},100)))}}}(),_boxeverq=_boxeverq||[];
function __boxever(){this.version="1.3.5";this.client_key;this.target;this.cookie_name;this.cookie_domain;this.cookie_path="/";this.cookie_expires_days=730;this.browser_id="anonymous";this.cross_domain_origin;this.cross_domain_url;this.token_counter=1;this.proxy_url="boxever-proxy.html";this.token=0;this.event=null;this.flag_ttl=24E5;__boxeverQueue=function(){this.push=function(){for(var a=0;a<arguments.length;a++)try{if("function"===typeof arguments[a])arguments[a]()}catch(b){BoxeverJERS.errors.push(b)}}};
this.setCookie=function(a,b,c){b=encodeURI(b);if("undefined"!==typeof c&&null!==c){var d=new Date;d.setDate(d.getDate()+c);b=b+"; expires\x3d"+d.toUTCString()}b=b+"; path\x3d"+this.cookie_path;"undefined"!==typeof this.cookie_domain&&null!==this.cookie_domain&&0<this.cookie_domain.length&&(b=b+"; domain\x3d"+this.cookie_domain);document.cookie=a+"\x3d"+b};this.getCookie=function(a){var b,c,d,h=document.cookie.split(";");for(b=0;b<h.length;b++)if(c=h[b].substr(0,h[b].indexOf("\x3d")),d=h[b].substr(h[b].indexOf("\x3d")+
1),c=c.replace(/^\s+|\s+$/g,""),c==a)return d=decodeURI(d)};this.storage=null;this.consoleLogData=function(a){};this.getVersion=function(){return this.version};this.getID=function(){return this.browser_id};this.getClientKey=function(){return this.client_key};this.getTarget=function(a){return a?this.target.replace("v1.2","v"+a):this.target};this.getCookieName=function(){return this.cookie_name};this.getCookieDomain=function(){return this.cookie_domain};this.getCookiePath=function(){return this.cookie_path};
this.getCookieExpiresDays=function(){return this.cookie_expires_days};this.reset=function(){_boxeverq=[];this.storage&&this.storage.removeItem(this.cookie_name);this.init()};this.resetCookieName=function(){this.storage&&this.storage.removeItem(this.cookie_name)};this.getURLParameter=function(a){return decodeURIComponent(((new RegExp("[?|\x26]"+a+"\x3d([^\x26;]+?)(\x26|#|;|$)")).exec(location.search)||[,""])[1].replace(/\+/g,"%20"))||null};this.checkCookieEnabled=function(){var a=!1;try{this.setCookie("boxever_test",
"text_value",1),a="text_value"==this.getCookie("boxever_test"),this.setCookie("boxever_test","text_value",-1)}catch(b){}return a};this.checkStorageEnabled=function(){return BoxeverStorage.storageAvailable()};this.initRegular=function(){var a=this.storage.getItem(this.cookie_name);void 0!=a&&null!=a&&0<a.length?(this.storage.setItem(this.cookie_name,a,this.cookie_expires_days),this.browser_id=a,a=_boxeverq,_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,a)):this.browserCreate("{}",function(a){try{void 0!=
a&&void 0!=a.ref&&(_boxever.browser_id=a.ref,_boxever.storage.setItem(_boxever.cookie_name,_boxever.browser_id,_boxever.cookie_expires_days),a=_boxeverq,_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,a))}catch(c){throw BoxeverJERS.errors.push(c),c;}},"json")};this.addUTMParams=function(a){var b;try{decodeURIComponent(window.location.search),b=decodeURIComponent}catch(c){try{unescape(window.location.search),b=unescape}catch(d){}}if(b){for(var h,m=/\+/g,q=/([^&=]+)=?([^&]*)/g,l=window.location.search.substring(1),
k={};h=q.exec(l);)k[b(h[1].replace(m," "))]=b(h[2].replace(m," "));for(var n in k)if(0==n.indexOf("utm_")||0==n.indexOf("UTM_")||"b_cer"===n||"utr"===n)a[n]=k[n]}return a};this.callIfFlagIsFalse=function(a,b,c){var d=!1;this.checkStorageEnabled()&&(d=BoxeverStorage.get(a,!1));try{if(!d&&(b(),this.checkStorageEnabled())){var h=this.flag_ttl;void 0!==c&&(h=c);BoxeverStorage.set(a,!0,{TTL:h})}}catch(m){BoxeverJERS.errors.push(m)}};this.eventPublish=function(a,b,c){c=this.target.split("/v")[0];var d=
this.target.split("/v")[1];a=this.proxy_url+"?token\x3d"+this.token_counter+"\x26baseUrl\x3d"+c+"\x26version\x3d"+d+"\x26client_key\x3d"+this.client_key+"\x26event\x3d"+encodeURIComponent(__JSON.stringify(a));this.token_counter++;c=document.createElement("iframe");c.style.display="none";c.width="0";c.height="0";c.src=a;document.body.appendChild(c);b()};this.isCookied=function(){var a=this.storage.getItem(this.cookie_name);return void 0!=a&&null!=a&&0<a.length};this.consume=function(){1<this.token&&
this.initRegular()};this.onCookieConsume=function(){_boxever.isCookied()?_boxever.consume():setTimeout(function(){_boxever.onCookieConsume()},10)};this.initConsumer=function(){var a=this.getURLParameter("token"),b=this.getURLParameter("event");if("undefined"!==typeof a&&null!=a&&"undefined"!==typeof b&&null!=b)if(this.token=a,this.event=__JSON.parse(b),_boxeverq.push(function(){_boxever.event.browser_id=_boxever.getID();_boxever.eventCreate(_boxever.event,function(a){},"json")}),1==a)this.initRegular();
else this.onCookieConsume();else BoxeverJERS.errors.push("consumer token or event is undefined or null")};this.initPublisher=function(){this.eventCreate=this.eventPublish;var a=_boxeverq;_boxeverq=new __boxeverQueue;_boxeverq.push.apply(_boxeverq,a)};this.initCrossDomain=function(){if(navigator&&navigator.userAgent)var a=/^((?!chrome|android).)*safari/i.test(navigator.userAgent),b=12<=Number(navigator.userAgent.split("Version/").pop().substr(0,2));else b=a=!1;var c=this.getCookie(this.cookie_name);
if(void 0!=c&&null!=c&&0<c.length)this.browser_id=c,c=_boxeverq,_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,c);else if(this.checkCookieEnabled()){var c=this.cross_domain_origin,d=this.cross_domain_url,d=d+"?",d=d+"client_key\x3d"+encodeURIComponent(this.getClientKey()),d=d+"\x26",d=d+"parent_url\x3d"+encodeURIComponent(window.location);BoxeverCrossDomain.receiveMessage(function(c){try{void 0!=c&&void 0!=c.data&&"string"==typeof c.data&&36==c.data.length&&(_boxever.browser_id=c.data,
a&&b?_boxever.setCookie(_boxever.getCookieName(),c.data,_boxever.getCookieExpiresDays()):_boxever.setCookie(_boxever.getCookieName(),c.data),c=_boxeverq,_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,c))}catch(d){throw BoxeverJERS.errors.push(d),d;}},c);document.getElementsByTagName("body")[0].appendChild(function(){var a=document.createElement("iframe");a.style.cssText="visibility:hidden;display:none";a.width=0;a.height=0;a.src=d;return a}())}};this.validateSettings=function(a){if(!a.hasOwnProperty("client_key"))throw Error("Configuration property 'client_key' is required");
if(!a.hasOwnProperty("target"))throw Error("Configuration property 'target' is required");if(!a.hasOwnProperty("cookie_domain"))throw Error("Configuration property 'cookie_domain' is required");};this.initSettings=function(){this.validateSettings(_boxever_settings);this.client_key=_boxever_settings.client_key;this.cookie_name="bid_"+_boxever_settings.client_key;this.target=_boxever_settings.target;this.cookie_domain=_boxever_settings.cookie_domain;"undefined"!=typeof _boxever_settings.publisher?"undefined"!=
typeof _boxever_settings.publisher.url&&(this.proxy_url=_boxever_settings.publisher.url):"undefined"!==typeof _boxever_settings.cross_domain&&("undefined"!=typeof _boxever_settings.cross_domain.origin&&(this.cross_domain_origin=_boxever_settings.cross_domain.origin),"undefined"!=typeof _boxever_settings.cross_domain.url&&(this.cross_domain_url=_boxever_settings.cross_domain.url));this.checkCookieEnabled()?this.storage={setItem:function(a,b,c){_boxever.setCookie(a,b,c)},getItem:function(a){return _boxever.getCookie(a)},
removeItem:function(a){_boxever.setCookie(a,"",-1);return!0}}:this.checkStorageEnabled()&&(this.storage={setItem:function(a,b,c){BoxeverStorage.set(a,b,c)},getItem:function(a,b){return BoxeverStorage.get(a,b)},removeItem:function(a){return BoxeverStorage.deleteKey(a)}})};this.init=function(){var a=navigator&&navigator.userAgent?/^((?!chrome|android).)*safari/i.test(navigator.userAgent):!1,b=this.getCookie(this.cookie_name),b=void 0!=b&&null!=b&&0<b.length;try{if(this.initSettings(),this.storage||
"undefined"!=typeof _boxever_settings.publisher)"undefined"!=typeof _boxever_settings.publisher?this.initPublisher():"undefined"!=typeof _boxever_settings.consumer?this.initConsumer():"undefined"===typeof _boxever_settings.cross_domain||a&&(!a||b)?this.initRegular():this.initCrossDomain()}catch(c){throw BoxeverJERS.errors.push(c),c;}}}var Boxever=Boxever||new __boxever;
(function(a){a.get=function(a,c){""===c&&(c="BoxeverUtils.consoleLogData");BoxeverJSONP.exec(a+"\x26callback\x3d?",c)};a.post=function(a,c,d){""===d&&(d="BoxeverUtils.consoleLogData");var h="",h=BoxeverXML.isXML(c)?BoxeverXML.xml2string(c):"string"===typeof c&&"\x3c"==c.charAt(0)?c:"string"===typeof c&&"{"==c.charAt(0)?__JSON.stringify(__JSON.parse(c)):__JSON.stringify(c);a=-1==a.indexOf("?")?a+"?":a+"\x26";a=a+"message\x3d"+encodeURIComponent(h)+"\x26callback\x3d?";BoxeverJSONP.exec(a,d)}})(Boxever);
(function(a){function b(b,c,d,h,g,e){var f=a.getTarget(),f=f+"/"+b,f=f+"/create.",f=f+h,f=f+"?",f=f+"client_key\x3d"+a.getClientKey();"undefined"!=typeof g&&(f=f+"\x26boxever_version\x3d"+g);"undefined"!=typeof e&&(f=f+"\x26content_version\x3d"+e);a.post(f,c,function(b){try{if("NOT_FOUND"===b.status&&"Invalid browser id/ref specified"===b.error_msg){var e="Resetting cookie name for browser id/ref "+a.getID()+" for client_key "+a.getClientKey();a.resetCookieName();BoxeverJERS.errors.push(e)}}catch(c){}d(b)})}
function c(b,c,d,h,g){var e=a.getTarget(),e=e+"/"+b,e=e+"/create.",e=e+g,e=e+"?",e=e+"client_key\x3d"+a.getClientKey(),e=e+"\x26",e=e+"api_token\x3d"+d;a.post(e,c,h)}function d(b,c,d,h,g){var e=a.getTarget(),e=e+"/"+b,e=e+"/",e=e+c,e=e+"/show.",e=e+g,e=e+"?",e=e+"client_key\x3d"+a.getClientKey(),e=e+"\x26",e=e+"api_token\x3d"+d;a.get(e,h)}function h(b,c,d,h,g){var e=a.getTarget(),e=e+"/"+b,e=e+"/search.",e=e+g,e=e+"?",e=e+"client_key\x3d"+a.getClientKey(),e=e+"\x26",e=e+"api_token\x3d"+d;null!==c&&
0<c.indexOf("\x3d")&&(d=c.indexOf("\x3d"),b=encodeURIComponent(c.substring(0,d)),c=encodeURIComponent(c.substring(d).replace("\x3d","")),e+="\x26",e=e+b+"\x3d"+c);a.get(e,h)}function m(b,c,d,h,g,e){var f=a.getTarget(),f=f+"/"+b,f=f+"/",f=f+c,f=f+"/update.",f=f+e,f=f+"?",f=f+"client_key\x3d"+a.getClientKey(),f=f+"\x26",f=f+"api_token\x3d"+h;a.post(f,d,g)}function q(b,c,d,h,g,e){var f=a.getTarget(),f=f+"/"+b,f=f+"/",f=f+c;null!==d&&0<d.length&&(f=f+"/"+encodeURIComponent(d));f+="/delete.";f+=e;f+="?";
f=f+"client_key\x3d"+a.getClientKey();f+="\x26";f=f+"api_token\x3d"+h;a.get(f,g)}a.pingCreate=function(a,c,d){b("ping",a,c,d)};a.eventCreate=function(a,c,d){b("event",a,c,d,"1.3.5","undefined"!=typeof _boxever_content_version?_boxever_content_version:void 0)};a.eventShow=function(a,b,c,h){d("event",a,b,c,h)};a.eventSearch=function(a,b,c,d){h("event",a,b,c,d)};a.browserCreate=function(a,c,d){b("browser",a,c,d)};a.browserShow=function(a,b,c,h){d("browser",a,b,c,h)};a.customerCreate=function(a,b,d,h){c("customer",
a,b,d,h)};a.customerShow=function(a,b,c,h){d("customer",a,b,c,h)};a.customerUpdate=function(a,b,c,d,g){m("customer",a,b,c,d,g)};a.customerDelete=function(a,b,c,d,g){q("customer",a,b,c,d,g)};a.customerSearch=function(a,b,c,d){h("customer",a,b,c,d)};a.customerDataCreate=function(a,b,d,h){c("customerdata",a,b,d,h)};a.customerDataShow=function(a,b,c,h){d("customerdata",a,b,c,h)};a.customerDataUpdate=function(a,b,c,d,g){m("customerdata",a,b,c,d,g)};a.customerDataDelete=function(a,b,c,d,g){q("customerdata",
a,b,c,d,g)};a.campaignCreate=function(a,c,d){b("campaign",a,c,d)};a.campaignShow=function(a,b,c){d("campaign",ref,api_token,b,c)};a.campaignSearch=function(a,b,c,d){h("campaign",a,b,c,d)};a.auditShow=function(a,b,c,h){d("audit",a,b,c,h)};a.auditSearch=function(a,b,c,d){h("audit",a,b,c,d)};a.profileCreate=function(a,c,d,h){b("profile",a,d,h)};a.profileShow=function(a,b,c,h){d("profile",a,b,c,h)};a.profileUpdate=function(a,b,c,d,g){m("profile",b,a,c,d,g)};a.profileSearch=function(a,b,c,d){h("profile",
a,b,c,d)}})(Boxever);(function(a){function b(b,d,h){var m=a.getTarget("2"),m=m+"/"+b;a.post(m,d,h)}a.flowExecutionCreate=function(a,d){b("flowExecutions",a,d)};a.callFlows=function(a,d){b("callFlows",a,d)}})(Boxever);var _boxever=Boxever;_boxever.init();